### ISSUE TITLE
[BUG] Cant pass InventoryClick Event

### ISSUE THREAD

**Issue by iceBear67** [Server-CT/ManiHunt#9]
Could not pass event InventoryClickEvent to ManHunt v1.0-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2277) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:941) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
        at io.ib67.manhunt.game.Game.lambda$start$4(Game.java:81) ~[?:?]
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_261]
        at io.ib67.manhunt.game.Game.start(Game.java:77) ~[?:?]
        at io.ib67.manhunt.game.Game.lambda$joinPlayer$8(Game.java:176) ~[?:?]
        at io.ib67.manhunt.gui.Vote.vote(Vote.java:92) ~[?:?]
        at io.ib67.manhunt.gui.Vote.onClick(Vote.java:122) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        ... 18 more

**Comment by iceBear67** [comment]
原提交人表示开启正版验证后修复

**Comment by iceBear67** [comment]
`if (e.getPlayer().getUniqueId().equals(runner.getUniqueId())) {`
或与 Vote 选举 Runner 失败有关

**Comment by iceBear67** [comment]
~顺便测试一下bot~

**Comment by iceBear67** [comment]
`您好，我们三个人，因为一个人未拥有minecraft正版，所以我的服务器关闭了正版验证，此时每次投票都显示的是"您投给了 null"，我认为很有可能是未开启正版验证无法get到玩家的UUID，所以后来我开启了正版验证，然后可以正常投票，并继续游戏了~这真的是一个很不错的插件，感谢您！`
就是vote的问题了

**Comment by iceBear67** [comment]
应该和 #15 有关系。  
#15 已经closed了，等待测试。

**Comment by iceBear67** [comment]
solved
